[package]
name = "tetris_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["bmp", "wav","mp3","bevy_dev_tools"] }
rand = "0.8.5"


[profile.dev] # 项目在开发模式下使用 1 级优化
opt-level = 1
[profile.dev.package."*"] # 项目依赖在开发模式下使用 3 级优化
opt-level = 3
